### ISSUE TITLE
Warn user about not installing newest version

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-package#145]
For example, running `elm-package install` in a directory whose `elm-package.json` contains
```json
    "dependencies": {
        "elm-lang/core": "2.1.0 <= v < 3.0.0",
        "evancz/start-app": "2.0.0 <= v < 2.0.1"
    },
```
currently gives:
```shell
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0
    evancz/elm-effects 1.0.0
    evancz/elm-html 4.0.1
    evancz/start-app 2.0.0
    evancz/virtual-dom 2.0.0

Do you approve of this plan? (y/n)
```
I'd rather like to see something like:
```shell
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0
    evancz/elm-effects 1.0.0 (latest package version is 2.0.0)
    evancz/elm-html 4.0.1
    evancz/start-app 2.0.0 (latest package version is 2.0.1)
    evancz/virtual-dom 2.0.0

Do you approve of this plan? (y/n)
```

**Comment by jvoigtlaender** [comment]
I think I know how to add this feature. May I?

**Comment by evancz** [comment]
I messed up missing this issue! I switched to readonly where I look at issues when I'm focusing on the project rather than getting notified all the time.

Yes, for sure, I think this would be quite helpful. I think it makes sense to switch to optimistic concurrency, so I added you to the @elm-lang/packages team. You can now do stuff with this repo. The general setup should be, do all work on your fork, bring it into this repo in big chunks with an overview of what is changing and why. This will mean the default for your PRs is "yes" and I will be able to do periodic systematic reviews and freeze certain branches in the lead up to a release.

**Comment by jvoigtlaender** [comment]
I implemented this in https://github.com/elm-lang/elm-package/pull/191.

**Comment by jvoigtlaender** [comment]
Closing for its pull request.
