### ISSUE TITLE
0.5.1 is incompatible with ghc 7.10.2

### ISSUE THREAD

**Issue by Magicloud** [elm-lang/elm-package#147]
```
src/Docs.hs:21:5:
    Non type-variable argument
      in the constraint: Control.Monad.Error.Class.MonadError [Char] m
    (Use FlexibleContexts to permit this)
    When checking that ‘badJson’ has the inferred type
      badJson :: forall (m :: * -> *) a.
                 Control.Monad.Error.Class.MonadError [Char] m =>
                 [Char] -> m a
    In an equation for ‘generate’:
        generate
          = do { Cmd.run "elm-make" ["--docs=" ++ Path.documentation];
                 json <- liftIO (BS.readFile Path.documentation);
                 either badJson return (Json.eitherDecode json) }
          where
              badJson msg
                = throwError $ "Problem with generated documentation:\n" ++ msg```

**Comment by jvoigtlaender** [comment]
It's not really incompatible. It just needs the `FlexibleContexts` language pragma. This is addressed in the build script linked at https://github.com/elm-lang/elm-platform by [this line](https://github.com/elm-lang/elm-platform/blob/775e6fa5687f73f1c95a721cec2abb01e25d2eee/installers/BuildFromSource.hs#L143).

And looking beyond `0.5.1`, the matter is fixed by this commit: https://github.com/elm-lang/elm-package/commit/af517f2ffe15f8ec1d8c38f01ce188bbdefea47a.

So, the issue here can be immediately closed.

**Comment by Magicloud** [comment]
Ah, did not read through the building script.
