### ISSUE TITLE
elm package install fails on Windows 10

### ISSUE THREAD

**Issue by FunkySoft45** [elm-lang/elm-package#225]
I have this particular error when I try to launch a elm package install on Windows 10. I tried it on powershell, cmd and gitbash. Same results when I launched them as an administrator.

`elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 4.0.1
    elm-lang/html 1.0.0
    elm-lang/virtual-dom 1.0.2
    evancz/elm-graphics 1.0.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
elm-package.exe: elm-lang-core-fd9e702: MoveFileEx "elm-lang-core-fd9e702" "4.0.1": permission denied (Access is denied.)
`

Here is my elm-package.json :

{
    "version": "1.0.0",
    "summary": "Procedural Content Generation",
    "repository": "https://github.com/FunkySoft45/elm-pcg.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "4.0.1 <= v < 5.0.0",
        "elm-lang/html": "1.0.0 <= v < 2.0.0",
        "evancz/elm-graphics": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}

Any idea ? I know this particular problem has been discussed here in previous threads. But I couldn't find any suitable solution.

**Comment by dtsao** [comment]
FYI - I am seeing similar errors on Windows 8.1 and elm package 0.17.0. The problem is intermittent and happens maybe 1 out of 4 times when adding a new package. When I get the error, I rerun "elm package install" again until it succeeds (usually on the first try). 

This problem is similar to what was reported in issues: #139 and #23.

**Comment by evancz** [comment]
Sorry for the trouble. The way things are downloaded changed a bit with the 0.17.1 patch release that is out today, so this may be resolved.

If this can still happen with 0.17.1, please open a new issue with the print out from that.

**Comment by dtsao** [comment]
FYI - I ran into the same intermittent errors using 0.17.1, but determined that the problem was being caused by a conflict between the iDrive cloud backup software (https://www.idrive.com/) that was running on my PC and elm-package.exe. The iDrive service was holding a handle open to a temporary file that elm-package.exe was trying to rename, causing the access denied errors. With iDrive's service stopped, I can no longer reproduce the errors.

**Comment by davidmason** [comment]
Same issue in 0.18.0 caused by Dropbox. Worked immediately when I closed Dropbox before running `elm-package install`

**Comment by mewhit** [comment]
Same issue in 0.18.0 caused by Atom or/and Google Drive . Worked immediately when i closed both before running elm-package install
