### ISSUE TITLE
elm-get install sometimes fails on Windows 7

### ISSUE THREAD

**Issue by deadfoxygrandpa** [elm-lang/elm-package#23]
On Windows 7, running ```elm-get install [some library]``` will occasionally (rarely) fail with an MoveFileEx error (permission is denied). The error will appear something like this:

```
>elm-get install timthelion/elm-inputgroups
Cloning repo timthelion/elm-inputgroups
elm-get: elm-inputgroups: MoveFileEx "elm-inputgroups" "timthelion-elm-inputgroups": permission denied (Access is denied.)
```

You must manually delete the newly created directory then run the command again and it will usually work.

I'm pretty sure it's related to this issue: http://social.msdn.microsoft.com/Forums/vstudio/en-US/efe2b58b-fe2f-470b-9e46-c5bf73d35a65/movefileex-fails-with-access-denied-on-windows-7?forum=vcgeneral which would mean there's probably nothing we can do to fix it, but it would probably be possible to improve the user experience a bit if it does happen to fail. Maybe automatically retrying or something, but at least deleting the directory automatically so immediately trying to run the command again doesn't lead to this:

```
>elm-get install timthelion/elm-inputgroups
Cloning repo timthelion/elm-inputgroups

Error: failure when running: git clone --progress https://github.com/timthelion/elm-inputgroups.git
fatal: destination path 'elm-inputgroups' already exists and is not an empty directory.
```

**Comment by deadfoxygrandpa** [comment]
This isn't really relevant anymore, and I haven't seen this happen with elm-package

**Comment by evancz** [comment]
Thanks for closing this! With `elm-package` you actually get versions by downloading .zip files instead of running `git clone` so I suspect that's what fixed it.

**Comment by jkbits1** [comment]
I'm posting this comment in this closed thread as a FYI, partly because it's been noted as not occurring any more.

I found this github issue after encountering this problem after upgrading elm to 0.15. It's been resolved after following the guidance explained here.

After installing 0.15, I deleted the entire packages folder (in my elm development folder) as it appeared that my code was trying to use core version 1.1.0 and being confused by imports without the exposing syntax. I thought I'd changed my elm-package.json correctly, but perhaps not.

On running elm-package install, I had the problem for elm-html. After deleting the entire pacakges folder again, the issue occurred for elm-lang-core. On once again deleting the entire packages folder, the issue occurred with elm-lang-core for a second time.

On reading the first comment of this issue more carefully, I deleted only the core folder within the packages folder. This time, elm-package install worked.

As my 0.15 code (using Mailboxes) is now working and I no longer get errors running the code, I'm assuming the set-up is now fine.
