### ISSUE TITLE
package.elm-lang.org DNS lookups failing

### ISSUE THREAD

**Issue by keithasaurus** [elm-lang/elm-package#282]
[https://www.whatsmydns.net/#A/elm-lang.org](https://www.whatsmydns.net/#A/elm-lang.org)

The link above should show a lack of ability to resolve the IP for elm-lang.org in several places. Was there an IP change?

Practically, I'm unable to install packages, and a curl yields the following:
```
curl http://package.elm-lang.org
curl: (6) Could not resolve host: package.elm-lang.org
```
 

I didn't see a place for submitting issues on the website, so apologies if this is the wrong place.

**Comment by somlor** [comment]
My CI server is also reporting a DNS failure:
```
Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-08-24%2019%3A44%3A12.624292%20UTC>
FailedConnectionException2 "package.elm-lang.org" 80 
False getAddrInfo: does not exist (Temporary failure in name resolution)
```

Interestingly the URL `http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-08-24%2019%3A44%3A12.624292%20UTC` returns `null` 👀 

![](http://i.imgur.com/BrFphaO.png)

Whereas truncating the timestamp from the URL returns a payload: `http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-08-24`

![](http://i.imgur.com/ajFqxzS.png)

**Comment by keithasaurus** [comment]
FWIW you can do a temp fix by adding this line to /etc/hosts
`107.170.159.76 package.elm-lang.org`

**Comment by oppai** [comment]
`package.elm-lang.org` is hosted by DreamHost.
http://elm-lang.org.w3lookup.net/

 DreamHost has any problems about connection. 
https://twitter.com/DreamHostCare/status/900855897383202816

I have same issue that cant resolve domain from AWS.

**Comment by evancz** [comment]
The root issue was the DreamHost DNS was having trouble today. Migrating to a different DNS seemed like a bad way to approach the issue, so there was no practical action to take. Like I shared on Slack, you can work around it by using the hosts file idea that @keithasaurus mentioned.
