### ISSUE TITLE
elm-get doesn't resolve with github tags correctly

### ISSUE THREAD

**Issue by jcollard** [elm-lang/elm-package#33]
elm-get doesn't seem to be able to find tags that are not in the catalog even if they exist on github.

In an empty directory on Ubuntu 14.04 x86_64:

`elm-get install jcollard/Playground 0.2.3.2`

Produces:

```
Your project does not have a elm_dependencies.json file, which the Elm
compiler needs to detect dependencies. Should I create it? (y/n): y
Cloning repo jcollard/Playground

Error: could not find version 0.2.3.2 on github.
```

**Comment by evancz** [comment]
As of `elm-package` I think this issue is "How do we grab arbitrary code from github and use it as a package?" I think this is covered by #87 and my general idea is that this can be resolved by running a local package catalog that is backed by github (in addition to the global one that has nice guarantees).
