### ISSUE TITLE
Silent Failure/Confusion when Package Version Does Not Exist

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-package#86]
I tried depending on `elm-lang/core 1.1.0` without realizing it hadn't been uploaded yet. 

Run these commands in any directory with depdency `"elm-lang/core": "1.1.0 <= v < 2.0.0"`:

Running `elm-make` I get the error
```
Packages configured successfully!
your elm-package.json file says you depend on package elm-lang/core,
but it looks like it is not properly installed. Try running 'elm-package install'.
```
Running `elm-package install` or `elm-package install elm-lang/core 1.1.0` I get 
```
Packages configured successfully!
```
but nothing has changed, running `elm-make` gives the same message.

Seems like it should say version does not exist.

**Comment by evancz** [comment]
Interesting, I wonder if it is checking for the tag on github but *not* checking that it is published through the package site.

**Comment by sonnym** [comment]
Another instance of this same problem occurs when you specify a version that cannot be resolved, e.g. `2.0.0 <= v < 2.0.0`.  The original source can be found here:  https://github.com/elm-lang/elm-reactor/pull/90#issuecomment-91382002

**Comment by inou** [comment]
When one of the dependencies in `elm-package.json` is not in packages (either because is not published or someone made a mistake):
1. first `elm-package install` tries to remove all packages (leaves empty folders).
2. second `elm-package install` confirms that everything is ok - `Packages configures successfully!` but it's not - all dependencies are gone.

To reproduce:
1. `elm-make`
2. edit `elm-package.json` and add `"evancz/elm-svg": "2.0.0 <= v < 3.0.0"` to dependencies
3. `elm-package install` (adds deps)
4. change version of elm-svg to `"2.0.2 <= v < 3.0.0"`
5. `elm-package install` (tries to remove all deps) - press y 
Error - I think it should give warning that dependency is not found.
6. `elm-package install` gives `Packages configures successfully!`
Error - all deps are removed (including `elm-lang/core`)

Some warning about missing dependency would be nice.

**Comment by daveyarwood** [comment]
I'm new to Elm and not sure if this is related, but I am seeing the same behavior with a package version that *does* appear to exist. I'm trying to run the tests for the "hello world" exercise on [exercism.io](http://exercism.io). Here's the elm-package.json: https://github.com/exercism/xelm/blob/master/exercises/hello-world/elm-package.json

When I run `elm-test HelloWorldTests.elm`, I get the same error message about elm-lang/core not being installed properly:

```
your elm-package.json file says you depend on package elm-lang/core,
but it looks like it is not properly installed. Try running 'elm-package install'.
```

When I run `elm-package install`, I get:

```
Packages configured successfully!
```

But then when I run `elm-test HelloWorldTests.elm` again, I still get the same error message.

I tried re-installing Elm with the [Mac installer on the Elm website](http://elm-lang.org/install) and trying again, but got the same results.

In the elm-package.json for this project, the elm-lang/core dependency is `"2.0.0 <= v < 4.0.0"`, which seems like it ought to work; [it looks like there are 3 uploaded versions of elm-lang/core that fall in that range](http://package.elm-lang.org/packages/elm-lang/core). By the way, in cases like this, how does elm-package decide which version to install? Does it install the newest available version that satisfies the dependency?

**Comment by daveyarwood** [comment]
Ah, apparently my problem was related to using an older version of Elm (I tried Elm a long time ago) which I apparently installed via Cabal. This problem went away when I explicitly used `/usr/local/bin/elm-package install` and `/usr/local/bin/elm-test HelloWorldTests.elm`.

**Comment by evancz** [comment]
I'm going to guess this is the same as #116 and close in favor of that one.
