### ISSUE TITLE
Use YAML for elm-package instead of JSON

### ISSUE THREAD

**Issue by jasonkuhrt** [elm-lang/elm-package#94]
Would the community be open to YAML instead of JSON?

I have never understood why JSON is chosen over YAML especially for environments where humans are expected to type things. Its more verbose without substantive gains and does not support comments atoll. YAML is designed for and optimized for humans, JSON is conversely designed first for machines.

In spirit YAML also seems closer to the culture of ELM than JSON.

Thoughts?

**Comment by jasonkuhrt** [comment]
@johnpmayer As per your request:
```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/USER/PROJECT.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "1.1.0 <= v < 2.0.0"
    }
}
```
```yaml
version: 1.0.0
summary: helpful summary of your project, less than 80 characters
repository: https://github.com/USER/PROJECT.git
license: BSD3
source-directories: 
  - .
exposed-modules: []
dependencies: 
  elm-lang/core: 1.1.0 <= v < 2.0.0
  evancz/elm-markdown: 1.1.2 <= v < 2.0.0
```

More people know the format that they basically already use to jot down todos. I can tell you that `YAML` is *not* fringe, it is common.

**Comment by Apanatshka** [comment]
I like YAML better than JSON for tool config. JSON is a web thing and so is Elm. But the tools are "native", so it makes sense to use a nice format like YAML. As long as it's easy to parse/generate in Haskell of course. Because most of these files don't usually need manual change. Which also makes this issue kind of low-priority for me.

**Comment by jonathanhefner** [comment]
I agree YAML is more pleasant.  But if the Elm compiler is ever bootstrapped (written in Elm) it wouldn't be able to use a Haskell package to parse YAML.  There does appear to be a [js-yaml](https://github.com/nodeca/js-yaml), but, in this hypothetical future, should it be a compiler dependency?

What if we stole a trick from Lua, and wrote the package config in Elm?  See Premake [for an example](http://industriousone.com/sample-script) (that Lua script mutates global state, but I'm sure we could be more elegant ;).

**Comment by jasonkuhrt** [comment]
@jonathanhefner Can you take a best-guess conversion of the above into an elm-compatible design?

**Comment by jonathanhefner** [comment]
@jasonkuhrt Something closest to the Lua script would be:

```elm
config
  [ version "1.0.0"
  , summary "helpful summary of your project, less than 80 characters"
  , repository "https://github.com/USER/PROJECT.git"
  , license "BSD3"
  , sourceDirectories ["."]
  , exposedModules []
  , dependencies
      [ "elm-lang/core@1.1.0 <= v < 2.0.0"
      , "evancz/elm-markdown@1.1.2 <= v < 2.0.0"
      ]
  ]
```

Something closer to the original JSON would probably use Elm's [record syntax](http://elm-lang.org/learn/Syntax.elm#records).  Neither is as smooth as YAML, but what do you think?

**Comment by evancz** [comment]
Seems fine to have elm-package.yaml or elm-package.json, but I don't think it's a great idea.

I personally don't know anything about YAML, and I'm pretty good at programming I think. We know that anyone making webapps is eventually going to learn JSON. So it's reasonable to say "all Elm programmers should know JSON". Now if we ask "What percentage of JS coders and Elm coders already know about YAML?" Realistically, I can't imagine it's super high.

So I'm not super excited about having one extra thing to learn that's not transferrable. I think this has community implications in that if I see a project, now I need to learn YAML for no particularly strong reason. Tons of folks coming from JS use package.json to set things up in npm.

**Comment by Apanatshka** [comment]
That's an OK argument. I don't mind writing a bit of JSON and it's mostly used by tools anyway. 

Do realise it's a variation of the "backward-compatibility argument". And that argument can (easily?) be used too much, which has a stagnation effect of not moving to (newer) better technology.

**Comment by jasonkuhrt** [comment]
@evancz Indeed you should get a sense for yourself and include that data point(s) in the decision. I think you will find that `YAML` is known amongst lots of people, though certainly not all. YAML is widely used in the Ruby community, its widely known in the Node community, its about a decade-and-a-half old.

I personally don't understand the advantage of JSON in a community that is otherwise pushing a brighter and more elegant vision for making things. YAML is more succinct than JSON in every way. I've typed a lot of JSON in my life, and I resent it. YAML is a breath of fresh air. I've typed a lot of JSON where I had comma errors that were caught too late (pushed a package etc.).

I would only admit that the empty array and empty object cases in YAML are surprising because the syntax to express them only appears in those cases:

```yaml
foo:
  - a: 1
    b: 2
```
```yaml
foo: []
```
```yaml
foo:
  a: 1
  b: 2
```
```yaml
foo: {}
```

**Comment by jasonkuhrt** [comment]
- http://eslint.org/docs/configuring/ supports YAML and JSON. I would be really curious how many pick JSON over YAML.

**Comment by rtfeldman** [comment]
I agree with @evancz that learning curve is a critical consideration for a new language.

YAML is certainly known in the Rails community, as Rails uses it. I wouldn't say it's widely known in the Node community, though, except inasmuch as that community overlaps with Rails; I was into Node for several years before I touched Rails, and never used YAML in that entire time. I also can't think of a Node library that requires YAML (as opposed to supporting it as an alternative), so I don't think it's a safe assumption that Node developers know it.

Personally I think the only two options that make sense for configuration file formats are JSON and Elm. Even if YAML is a slight improvement over JSON, I don't think that outweighs the cost of introducing it. Neither JSON nor Elm have a learning curve cost, as it's safe to assume that everyone knows JSON, and that anyone who wants to write Elm programs will learn Elm. :smile:

I'm curious about the idea of doing the config files in Elm at some point. Maybe something like "The whole file is evaluated as a single Record Literal declaration,  and that record is then parsed as the config." The benefits of this would be:

1. Elm's Record syntax is slightly less verbose than JSON (e.g. because you don't have to put quotes around the keys)
2. You could use comments
3. The Elm compiler could verify the signature of the record, and give you familiar error messages if you messed something up - rather than ad-hoc error messages for incorrectly-typed JSON.

**Comment by jasonkuhrt** [comment]
> The Elm compiler could verify the signature of the record, and give you familiar error messages if you messed something up - rather than ad-hoc error messages for incorrectly-typed JSON.

I like this.

**Comment by JustusAdam** [comment]
Why not have both?

The expressiveness  of (safe) YAML and JSON is virtually identical and the Haskell library for parsing YAML (named 'yaml' (surprise)) uses the "FromJSON" and "ToJSON" typeclasses from 'aeson' anyway, which I assume is the way that elm-package parses json.

Adding YAML support would thusly only mean searching for an 'elm-package.yaml' or 'elm-package.yml' file should an 'elm-package.json' file not be found.

The default in-/output of elm-package and [elm-init](https://github.com/JustusAdam/elm-init) could still be JSON but you could use YAML as well, if you prefer it.

**Comment by rtfeldman** [comment]
The trouble with supporting multiple formats is that if N formats are supported, then everyone must learn all N or else be unable to understand whatever subset of all Elm packages use the formats they haven't learned. If there is 1 format, then everyone can learn 1 format and then be able to understand all Elm packages.

These are configuration files, so even if one format is better than another, its benefits are not going to be very large in the grand scheme of things. I don't think even the positive delta between the nicest imaginable configuration format and JSON would be greater than the negative introduced by allowing multiple formats. :smile:

**Comment by JustusAdam** [comment]
If the tools are sophisticated enough there should be no reason to ever look at one of those config files. However I agree with you. The only reason I'd consider it in this case is because here the difference is a purely syntactic one, not a semantic one.

The field names are the same and the data structures as well as their contents is the same. The only difference being the visual layout.

**Comment by jasonkuhrt** [comment]
Config files that are managed by tools (e.g. `.git/config`) are ideal but failing that, files designed for humans to read and enter text into should be in YAML. I routinely encounter systems that support YAML in a variety of communities that I travel through, I cannot imagine being convinced that JSON is somehow "easier" to understand than YAML. The fact that YAML is just about how people already naturally write structured todos/notes etc. speaks pretty highly IMO.

Anyways, I don't spend enough time in the Elm community to consider myself a member so will close this issue for now. If someone else wants to take it up re-open and go for it. Cheers.
